### ISSUE TITLE
Migrate from CircleCI to GitHub Actions

### ISSUE THREAD

**Issue by ajsantander** [Synthetixio/synthetix#1159]
### Summary
Improve and modernize current CI process of `synthetix` repository.

### Dev Tasks
- [x] Upgrade to nodejs 14
- [ ] Migrate current jobs from CircleCI to Github Actions
- [ ] Set up a GitHub Actions runner (if better specs are required than default one)
- [x] Add CodeQL workflow
- [x] Add dependabot config
- [x] Lock dependencies properly
- [ ] Improve dependency caching (use `package-lock.json` hash)
- [ ] Add eslint with sarif reports
- [ ] Add more security-oriented tools to the CI process like: `lockfile-lint` and dependency auditing

### QA Tasks
- [ ] CI should be all green 😄 
- [ ] Review associated PRs

Associated PR (wip): #1116

**Comment by drptbl** [comment]
New task:
https://github.com/Synthetixio/issues/issues/14
