### ISSUE TITLE
Protect smart contract wallet users from depositing in L2 contract level

### ISSUE THREAD

**Issue by JChiaramonte7** [Synthetixio/synthetix#1176]
### Dev Tasks
- [ ] Compensate users that lost funds
- [ ] Contracts should prevent smart account users from depositing
- [ ] Consider if withdrawals should be guarded as well: As brought up by Christian from Chainlink "Because of account abstraction on L2, there are no EOAs, all accounts have code"

### QA Tasks

**Comment by justinjmoses** [comment]
Closing in favor of #1153
