### ISSUE TITLE
Staking DApp => Earn Page. On Mainnet there is 0%APY shown

### ISSUE THREAD

**Issue by fritzschoff** [Synthetixio/synthetix#1674]
On L2 we see a %number but dunno if that is correct.
On L1 there is nothing if user didn't staked. 
I had a look in to the snxHolderQuery and saw that we don't query any data. See PR: https://github.com/Synthetixio/js-monorepo/pull/159
So I added the needed value. 
But there is an issue with the endpoint that we are querying, the `snxHolders`. The code `codegen-graph-ts` does some weird stuff with the string that should point to the endpoint. ![Bildschirmfoto 2022-02-01 um 19.13.59.png](https://images.zenhubusercontent.com/5d19e757a91f961fd8457e0f/345d19ad-f217-4de0-a2ae-47d7a4fd3023)
`sNXholders is not a Query` is the error you would get in the staking app.
Tested it by overriding that value in the  node_modules dir in the staking app and we get the first 1000 biggest stakers back. I guess we need to update the `codegen-graph-ts` ?

**Comment by cavalier-eth** [comment]
@fritzschoff is this ticket still required?

**Comment by bachstatter** [comment]
Fixed
