### ISSUE TITLE
Exchange UI error: call exception 

### ISSUE THREAD

**Issue by grigio** [Synthetixio/synthetix#169]
it seems the data on https://synthetix.exchange aren't loaded anymore, I get this error

```
1.cafdaec4.chunk.js:1 Uncaught (in promise) Error: call exception (address="0xba34e436C9383aa8FA1e3659D2807ae040592498", method="rateIsFrozen(bytes4)", args=[{"0":105,"1":66,"2":78,"3":66}], version=4.0.27)
    at Object.n [as throwError] (1.cafdaec4.chunk.js:1)
    at 1.cafdaec4.chunk.js:1
```

**Comment by grigio** [comment]
Now it seems to work, maybe it was just a partial deployment

**Comment by hav-noms** [comment]
It can happen when the DApps don't get all the blockchain data from failed requests from infura.io. usually a refresh or wait a bit before trying again.
