### ISSUE TITLE
Uniswap 900K gas estimation fixing solution

### ISSUE THREAD

**Issue by k06a** [Synthetixio/synthetix#243]
Related issues: https://github.com/ethereum/vyper/issues/1091, https://github.com/Uniswap/contracts-vyper/issues/39

We suggest to move _emit call before tokenFallback to resolve Uniswap 900K gas estimation. Solidity passes 63/64 of gas in subcalls and now estimator increases gas until 1/64 of gas left is enough for _emit call.

Currently gas estimator is feeding Uniswap proxy until 1/64 of gasleft would be enough for _emit call.

Moving _emit before tokenFallback would decrease gas estimation to 100K instead of 900K

![image](https://user-images.githubusercontent.com/702124/65262798-c8b9eb80-db13-11e9-989a-1c61cd58064a.png)

**Comment by k06a** [comment]
Also wrapping `tokenFallback` into `.call` and limiting its gas is a good idea. For example provide `Math.min(gasleft(), 200000)` of gas.

**Comment by k06a** [comment]
Same valid for all synth tokens. See for example sETH+ETH Uniswap pool transactions: https://etherscan.io/address/0xe9cf7887b93150d4f2da7dfc6d502b216438f244

**Comment by k06a** [comment]
It seems having some synths minted from user wallet, increases gas limit to 10M: https://www.reddit.com/r/synthetix_io/comments/djd6ca/uniswap_synthetix_gas_required_exceeds_allowance/

**Comment by k06a** [comment]
It is not also possible to swap SNX to DAI or any other token because of this bug.

**Comment by marc0olo** [comment]
@hav-noms why is this closed? I am not able to swap sETH to ETH on uniswap due to this bug

**Comment by ihlec** [comment]
@hav-noms the problem seams to still exists.

For certain transactions it would be useful to send the transaction with a default user defined gas limit after the gas estimation failed.

**Currently the users are facing unresponsive dApps.**

e.g. Uniswap:
`inpage.js:1 MetaMask - RPC Error: gas required exceeds allowance (12426210) or always failing transaction Object
(anonymous) @ inpage.js:1
index.tsx:283 estimateGas failed removeLiquidityETHWithPermit Array(10) Object
(anonymous) @ index.tsx:283
inpage.js:1 MetaMask - RPC Error: gas required exceeds allowance (12426210) or always failing transaction Object
(anonymous) @ inpage.js:1
index.tsx:283 estimateGas failed removeLiquidityETHWithPermitSupportingFeeOnTransferTokens Array(10) Object
(anonymous) @ index.tsx:283
index.tsx:295 This transaction would fail. Please contact support.`
