### ISSUE TITLE
Sirius Release: SIPs 16, 17, 18, 19 (26/09/2019)

### ISSUE THREAD

**Issue by garthtravers** [Synthetixio/synthetix#250]
This Thursday (AEST), we'll be deploying a new system upgrade to launch some of the recently approved SIPs. We will be taking down the system for several hours to deploy this release. During this time, users will be unable to interact with the system in any way, including using Mintr or Synthetix.Exchange, and transferring SNX or Synths.

Due to SIP 17, this release will also result in liquidity providers for the old sETH pool on Uniswap having their sETH frozen (as announced [here](https://blog.synthetix.io/action-required-seth-liquidity-providers-must-migrate-by-september-18/)). If anyone does not withdraw their liquidity in time, we will work with them to provide a solution.

Here's what will be included in this release:

- [SIP 16](https://sips.synthetix.io/sips/sip-16): Synthetix upgrades currently take longer than needed as the owner account makes up to 60 calls to configure the system. Most of these calls are setSynthetix and setFeePool on all of the Synths. We propose to point the Synths to the Synthetix Proxy and FeePool Proxy. This would reduce the amount of time the system is offline. Making upgrades a lot faster, cheaper (gas) and minimize the impact on users with reduced downtime.

- [SIP 17](https://sips.synthetix.io/sips/sip-17): This update will upgrade the currencyKeys from Bytes4 to Bytes32. This will enable Synthetix to create new Synths with symbols longer than 4 characters. e.g. sATOM, sDEFI, which is not currently possible with currencyKeys type defined as Bytes4.

- [SIP 18](https://sips.synthetix.io/sips/sip-18): This will recover the $2.9k sUSD that is currently unclaimable by minters in the SNX fee address. This sUSD is from the period in which there was a transfer fee for sending sUSD.

- [SIP 19](https://sips.synthetix.io/sips/sip-19): The Synthetix contracts still have transfer fees written into them, from before we disabled transfer fees in February 2018. Removing that code will optimise reclaim bytecode size required for new features.

This release is called 'Sirius,' which like future releases is named after a star (in order of visual magnitude).

**Comment by kaiynne** [comment]
Probably worth noting that SIP-16 is a big step in the right direction for decentralised proxy contracts. Alongs the testing we are doing with a the sETH pool rewards distribution I feel like we are making good progress on the upgrade front. We are also looking into implementing a time delay for releases (will be raising an issue for this soon), something suggested by Joey from Augur.
