### ISSUE TITLE
Need web3 query to get max_eth_to_convert, tokens_bought and reward_tokens

### ISSUE THREAD

**Issue by WyseNynja** [Synthetixio/synthetix#295]
I'm looking into building some automation that calls arbSynthRate on the ArbRewarder contract. The first thing I'm wanting to build is a dashboard that shows the maximum input ether along with the tokens + reward. Maybe I'm missing it, but I'm not seeing a way to get this information out of the contract since most of the methods are marked private. For now, I'm essentially re-implementing most of the calls in my own code.

I think it would be very helpful if there was a function that had a signature something like this:
```
function arbitrageAvailable() public view returns (uint max_input_ether, uint synth_output, uint synthetix_reward);
```

Then, every time a new block arrives, I can use web3 to query arbitrageAvailable.

Am I missing a better way to do this?

I also want to say that this contract is my favorite example of permissionless defi composability yet. Awesome work.

**Comment by justinjmoses** [comment]
Hey @WyseNynja, typically we want to keep contract sizes down and instead refer developers to querying the contract for these kinds of things, calculating values off-chain using on-chain information as reference. 

Right now [synthetix-js](https://github.com/Synthetixio/synthetix-js) is the best place to find JavaScript-based functionality to query the Synthetix contracts without having to load the ABIs yourself.

For example, to figure out how much SNX is left in the ArbRewarder:

```javascript
const { SynthetixJs } = require('synthetix-js'); // assumes node.js - if using browser then SynthetixJs is attached to `window`
const snxjs = new SynthetixJs();
const arbRewarder = '0xA6B5E74466eDc95D0b6e65c5CBFcA0a676d893a4';

snxjs.Synthetix.balanceOf(arbRewarder).then(value => {
  const snxRemaining = snxjs.utils.formatEther(value);
  console.log('The ArbRewarder has', snxRemaining, 'SNX remaining');

  snxjs.ExchangeRates.ratesForCurrencies(['SNX','ETH'].map(snxjs.utils.toUtf8Bytes32).then(([snx, eth]) => {
     const snxRate = snxjs.utils.formatEther(snx);
     const ethRate = snxjs.utils.formatEther(eth);

      // now you have the SNXUSD and ETHUSD rates, figure out how much ETH you can send
     const maxInputEther = snxRemaining * snxRate / ethRate;

      // huge success
  });
});
```

**Comment by WyseNynja** [comment]
Thank you. This is helpful.

However, I don't have a javascript environment setup. Can you please tell me what `['SNX','ETH'].map(snxjs.utils.toUtf8Bytes32)` returns?

**Comment by WyseNynja** [comment]
Nevermind. I figured it out:

```
assert_eq!(snx_bytes32, [83, 78, 88, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]);

assert_eq!(eth_bytes32, [69, 84, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]);

```

**Comment by justinjmoses** [comment]
No, I just threw something together to get you started. 

To get the uniswap ETH balance, you'll need to query the Uniswap contract (via it's address and ABI), for `balance` - or you can use the Uniswap Graph's endpont. 

If you want more help, please jump into the `#dev-portal` channel in our [Discord](https://discordapp.com/invite/AEdUHzt) -  there are more people in there who can help.
