### ISSUE TITLE
Tightening user incentives SCCP bundle

### ISSUE THREAD

**Issue by kaiynne** [Synthetixio/synthetix#296]
While the growth of Synthetix over the last few months has been incredible, there are still many aspects of the project that need significant improvement. We have discussed a number of these major architectural changes on the recent governance calls and they are critical to the success of the project, decentralised oracles being one example. There is a another category of change available within Synthetix, tuning parameters. This was the reason we separated SCCPs from SIPs to delineate minor parameter changes from protocol upgrades. This proposal will bundle a number of parameter tweaks I believe we need to implement in order to tune the feedback loops within the current system and align user incentives more clearly. The list of proposed changes are below:

1. Reduce claim window to 1 week (SIP-9)
2. Increase arb pool to 5% of weekly inflation
3. Reduce the c-ratio buffer from 10% to 1%
4. Increase the c-ratio to 1000%

-----

1. Firstly I think we need to revisit [SIP-9](https://sips.synthetix.io/sips/sip-9). This SIP was rejected several months ago, however, but if we implement this SIP we will reduce the amount of leveraging sETH that we are currently experiencing. When someone sells down sETH into the market to go long other crypto they are taking a risk that they will not be able to claim fees in the next period without buying back the sETH/sUSD on market later if the price of SNX falls. The longer a user can delay the need to burn and bring their ratio back into alignments the lower the risk. We are now seeing a number of users claiming on a biweekly schedule, this gives them up to 20 days potentially to repair their c-ratio. This period is too long and has lead to a steady erosion of the sETH/ETH peg over the last few weeks. This issue was obfuscated due to the demand to enter the sETH pool, as this demand has declined the selling pressure on sETH has increased to the point where we are now below .97 sETH/ETH ratio. By tightening the claim window to 1 week we will force all minters to repair their c-ratio within 13 days maximum or lose rewards. One of the objections to this change in the past was the cost of claims. With gas prices hovering around 1 gwei recently and gas optimisations about to go live this argument is far less valid.

2. The arb pool has been drained very quickly over the last few weeks. There are several reasons for this, the first is that some of the front-running bots are using it as a way of clearing out excess sETH profits they are holding. On the face of it this might seem like a less than ideal situation. But the reality is that the arb pool is absorbing excess supply directly that would otherwise be absorbed into the sETH pool itself impacting the peg. By increasing the supply to the arb contract we can more quickly absorb this excess supply of sETH and tighten the peg, in combination with proposal 1 to change the window where users can be undercollateralised without being penalised this should exert upward pressure on the peg.

3. Another aspect of the system that allows users to remain undercollateralised indefinitely is the c-ratio buffer. This was initially required to avoid users being slashed by rapid price drops in SNX when the original mechanism reduced fees by 25%+ if a user claimed while undercollateralised. Given that now a user will only have a tx fail, the need for this buffer to be so large has been removed. By changing the buffer to 1% we should see relatively few failed claims due to SNX price shifts, while raising the global c-ratio by 10% during times of SNX price decline.

4. Increasing the c-ratio to 1000% will help to rebalance the supply of Synths, there is still an excess supply of Synths in the market, and we have not yet seen demand catch up due to continued increase in SNX price. I do not think we will see a meaningful increase in Synth demand until we have several of the planned changes implemented, particularly the upgrade of sX to v2.0 planned for 4-6 weeks from now. During that time it is important that we realign supply and demand to restore the peg, raising the c-ratio has been an effective mechanism in the past and is likely to be effective this time as well.

The combination of these four changes is likely to be sufficient to restore the peg while we wait for the implementation of a number of protocol improvements over the next several months. It is important that we actively adjust the system parameters to reflect the current market dynamics and align incentives. These changes collectively should be extremely effective in doing so.

**Comment by CryptoToit** [comment]
Can't find fault with the reasoning... and need. Overall support this SCCP.

**Comment by hav-noms** [comment]
2,3,4 can be implemented ASAP via SCCPs
1 SIP9 will need to be in a future release 

Support all of this

**Comment by CryptoToit** [comment]
The one reservation I have, or should I say more of a request, around **"Reduce claim window to 1 week (SIP-9)"** is that there has to be supporting mechanism(s) in place that will make weekly claiming "easy". 

The one option is delegated management to a different account or we need something else as well... 

We need to realise that we are dealing with people to make the system work. People have lives and things happen. We cannot build a solution where we are dependent on people but make it difficult for them to claim **weekly** rewards. 

There has to be a mechanism that rewards are not missed because someone is traveling or not available to plug in his/her cold wallet to make the claims.

**Comment by kaiynne** [comment]
Based on the feedback above and in Discord, I am withdrawing the SIP-9 proposal. I think there is an opportunity to look at this again and potentially merge a solution to the snapshot gaming issue that has been discussed previously into a single SIP. So I will review that possible solution and resubmit SIP-9 later. I also think that we need more discussion to reach consensus on moving the c-ratio. The two other proposals appear to have solid consensus so I will write them up as SCCPs to be included in Rigil.
