### ISSUE TITLE
Mint, Burn and Claim in any Synth

### ISSUE THREAD

**Issue by charlierelaypay** [Synthetixio/synthetix#311]
Mintr Version 2 is live with bunch of enhancements and customer friendly short-cuts.
Synthetix, its dApps and Synths attract more users with increased awareness. 
In the beginning, Synthetix Team limited the mint/burn/claim functions with sUSD only. However, there was always an option for sophisticated users to use the contracts to mint/burn other Synths straight away without using sUSD as an interim Synth.

Platform is at scaling stage and removal of frictions will speed up the adoption.

In this issue, I propose the following enhancement;

As seen from the current Synth distribution, most of the users are holding/trading various Synths. It is time for Mintr to support other Synths for Mint/Burn and Claim functions while still keeping the simple sUSD option available.

**Mint Function:**

Mintr to allow users to Mint any Synth directly.

ie. User stakes SNX and has $500 USD available to Mint. User chooses sETH, sBTC or other s and inverse Synths to Mint directly. 

**Burn Function:**

Mintr to allow users to burn any Synth directly.

ie. User wants to Burn $500 USD worth of Synths. User chooses sETH, sBTC or other s and inverse Synths to Burn directly. 

**Claim Function:**

Currently Exchange Fees can only be collected as sUSD. Mintr to allow users collect the exchange fees in any Synth directly.

ie. User wants to claim $500 USD worth of Synths. User chooses sETH, sBTC or other s and inverse Synths to Claim directly. 

**Fee Considerations**

Currently, users directly Mint/Burn other Synths through contract, do not pay exchange fee. However, users interacting with Mintr interface to mint in other Synths follow sUSD => other Synths or the ones burning use other Synth => sUSD flow and generate transaction fees.

With this proposal, we need to decide whether transaction fee is applicable when a user Mint/Burn/Claim Synths, other than sUSD. 

My recommendation is Minting or Claiming any other Synth should be consider as a trading activity and should have a transaction fee. However, Burning any Synth should be fee free.

**Comment by deltatigernz** [comment]
I like it and would vote for standard fees on minting to any synth except susd. With burning from any synth no 'trading' fees

**Comment by traviagio** [comment]
Proposal makes a lot of sense. Minting any other Synth is indeed a trading activity and I would much rather be charged at Mintr interface than going to Synthetix.Exchange and doing the trade there. This is incentivising long term stakers and it adds additional revenue to the rewards pool.

**Comment by traviagio** [comment]
I assume this may also lead to a more diversified Synth pool as it makes it easier to mint Synths besides sUSD without having to go via Synthetix.Exchange first.

**Comment by garthtravers** [comment]
We've added a SIP for this and will be adding it in today's Vega release https://sips.synthetix.io/sips/sip-29
