### ISSUE TITLE
Hack Idea: Multicurrency Mintr

### ISSUE THREAD

**Issue by kaiynne** [Synthetixio/synthetix#321]
Fork Mintr to add support for every currency via a dropdown selector. Once selected all of the values will be denominated in the selected currency allowing you to burn/mint/claim fees in that currency.

**Comment by calchulus** [comment]
Do you mean that a user could mint directly to a synth rather than mint to SUSD (saves a step in transactions for the end user, but the onchain action actually does a market order right away for that synth in reality?

**Comment by hav-noms** [comment]
ah sorry @calchulus we've ditched the support for this in the smart contracts. I'll delete this hack idea now. 
Yes you used to be able to mint any synth directly onchain only as the dapps never supported it but it opened up front minting attacks that we needed to close.

Are you looking for hackathon ideas, contribute to the project or grants DAO ideas?

**Comment by calchulus** [comment]
Sure, happy to take a look at anything else you guys are curious about
adding

**Comment by kaiynne** [comment]
Worth noting as well that we can still handle this in the future by
updating Fee Reclamation to handle minting other synths, or even creating a
Mint + Exchange function that would trigger FR.

Kain Warwick
Founder
Synthetix.io
