### ISSUE TITLE
Looking for some examples for how to curl the Synthetix API

### ISSUE THREAD

**Issue by bitcoinmeetups** [Synthetixio/synthetix#376]
Looking for some examples for how to curl the Synthetix API

Hi,

I am testing out the Synthetix API at the moment. I am looking for some examples for how to curl the API. If you could post a couple of examples below that would be nice.

BM

**Comment by justinjmoses** [comment]
So as the backend is Ethereum, we supply the [`synthetix-js`](https://github.com/Synthetixio/synthetix-js) library as a mechanism to easily fetch state on-chain.

We do have an internal API that feeds some of https://dashboard.synthetix.io, however we are migrating to using The Graph, and have another utility to abstract away GraphQL requests to those endpoints: [`synthetix-data`](https://github.com/Synthetixio/synthetix-data). 

There is no documentation for the internal API we are using. You could either compile something yourself on-chain using synthetix-js, query via synthetix-data, or use a third party service like Dune Analytics or some such.
