### ISSUE TITLE
Rinkeby faucet

### ISSUE THREAD

**Issue by alfetopito** [Synthetixio/synthetix#382]
By any chance is there any sort of faucet for Rinkeby?

I'm looking only for a `sUSD` faucet at the moment.

Thanks

**Comment by hav-noms** [comment]
Hi @alfetopito yes there a faucet for SNX and sUSD. You can buy SNX or sUSD from the Synthetix Depot on these testnets.

https://contracts.synthetix.io/rinkeby/Depot
https://contracts.synthetix.io/ropsten/Depot
https://contracts.synthetix.io/kovan/Depot

For sUSD send ETH to the exchangeEtherForSynths function
![image](https://user-images.githubusercontent.com/1251099/73313665-ef392180-427f-11ea-9965-5022252ba7f5.png)

On the MAINNET Depot http://contracts.synthetix.io/Depot you can only get sUSD. SNX should be bought from uniswap.io/swap/0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f
