### ISSUE TITLE
Gas-reporter fails to log gas consumption in the output file when prod tests are run

### ISSUE THREAD

**Issue by i-stam** [Synthetixio/synthetix#722]
A mainnet fork is used and the prod tests are run instead.

Check #709 for instructions on spawining the environment and running the tests.

@cgewecke might be able to help with this one.

**Comment by cgewecke** [comment]
@i-stam 

Hi. Out of curiosity, did the codechecks report in CI also stop working?

**Comment by i-stam** [comment]
> @i-stam
> 
> Hi. Out of curiosity, did the codechecks report in CI also stop working?

Hi! The output report works fine for the unit tests:
`"test:gas": "buidler test --gas --optimizer || cat test-gas-used.log",`
which is what is being invoked in CI (`npm run test:gas && npx codechecks`)

The problem is when we try to run this:
```
"test:prod": "buidler test:prod --network localhost",
"test:prod:gas": "buidler test:prod --gas --network localhost --gas-output-file test-gas-used-prod.log",
```

**Comment by justinjmoses** [comment]
The output is an empty file.

Basically to reproduce, run `npm run fork -- --network mainnet` in one shell and in another run `npm run test:prod:gas`. 

When you `cat test-gas-used-prod.log` you'll see:

```
·------------------------|----------------------------|-------------------|-------------------------------------·
|  [90mSolc version: 0.5.16[39m  ·  [90mOptimizer enabled: false[39m  ·  [90mRuns: undefined[39m  ·  [90mBlock limit: 9007199254740991 gas[39m  │
·························|····························|···················|······································
|  [32m[1mMethods[22m[39m                                                                                                      │
··············|··········|··············|·············|···················|·················|····················
|  [1mContract[22m   ·  [1mMethod[22m  ·  [32mMin[39m         ·  [32mMax[39m        ·  [32mAvg[39m              ·  [1m# calls[22m        ·  [1musd (avg)[22m        │
·-------------|----------|--------------|-------------|-------------------|-----------------|-------------------·
```

**Comment by justinjmoses** [comment]
![image](https://user-images.githubusercontent.com/799038/93247729-bbeaca80-f75c-11ea-98f6-ecf2e5b7c73c.png)
