### ISSUE TITLE
Improvement Proposal for create new indexes

### ISSUE THREAD

**Issue by Draichi** [Synthetixio/synthetix#930]
## Creating Synths

from documentation:
> Our current cryptocurrency indexes are sDEFI and sCEX (and their inverses), which respectively track a basket of DeFi assets and a basket of centralised exchange tokens.

And if I had an idea for and a new index, how would I create one?

**Comment by justinjmoses** [comment]
The best way forward is to join discord and discuss your idea there with the community.
